"""Render the inbound carrier voice agent logic tree.

Single core tree (`core.mmd`) plus one drill-down (`negotiation.mmd`).
Both render to PNG via mermaid-cli. Output:

    docs/agent-logic-tree/rendered/core.png         <-- start here
    docs/agent-logic-tree/rendered/negotiation.png

Plus a thin index markdown at `docs/agent-logic-tree.md` that embeds both
PNGs and links to the source `.mmd` files.

Usage:
    python scripts/build_logic_tree.py                # render PNGs + index md
    python scripts/build_logic_tree.py --no-render    # markdown only
    python scripts/build_logic_tree.py --svg          # also produce SVG

Renderer detection:
    1. `mmdc` on PATH (mermaid-cli installed globally)
    2. `npx -y -p @mermaid-js/mermaid-cli mmdc` (npx fetches on demand)
    3. Print install hint and skip rendering
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TREE_DIR = REPO_ROOT / "docs" / "agent-logic-tree"
RENDERED_DIR = TREE_DIR / "rendered"
OUTPUT_MD = REPO_ROOT / "docs" / "agent-logic-tree.md"

# (filename, heading, render width)
DIAGRAMS = [
    ("core.mmd",        "Workflow tree",                              1800),
    ("negotiation.mmd", "Negotiation drill-down",                     1800),
]

PREAMBLE_TEMPLATE = """\
# Inbound Carrier Voice Agent — Logic Tree

> **Generated by** `scripts/build_logic_tree.py` on __TIMESTAMP__.
> Edit the `.mmd` files in `docs/agent-logic-tree/`, re-run the script.

The agent's complete decision logic in two diagrams:

1. **Core tree** — every key event from inbound call to dashboard write.
   FMCSA collapses to one node; the negotiation node is a drill-down marker.
2. **Negotiation drill-down** — the 3-persona, 3-round loop with floor guard
   and anti-renegotiation rule. Referenced from the core tree's `Negotiate` node.

**Visual conventions** (consistent across both diagrams):

| Color | Meaning |
|---|---|
| Amber rounded | Entry / start |
| Blue rectangle | Agent action |
| Peach diamond | Decision branch |
| Purple double-rect | Tool call (verify_carrier, search_loads_by_lane, Transfer Popup) |
| Teal thick-border | Sub-process reference (drill into another diagram) |
| Pink rounded | Negotiation persona (sub-tree only) |
| Green circle | Success terminal (BOOKED) |
| Red circle | Decline terminal (tagged outcome) |
| Gold rectangle | Post-call automated chain |
| Indigo cylinder | Data store (Twin Postgres → Dashboard) |
| Gray dashed | Side annotation (guardrails / tool retries / eager parallel) |

---
"""


def read_mermaid(path: Path) -> str:
    if not path.exists():
        sys.exit(f"missing source: {path}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def assemble_markdown() -> str:
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    parts = [PREAMBLE_TEMPLATE.replace("__TIMESTAMP__", timestamp)]
    for filename, heading, _ in DIAGRAMS:
        stem = Path(filename).stem
        body = read_mermaid(TREE_DIR / filename)
        png_path = RENDERED_DIR / f"{stem}.png"
        png_rel = f"agent-logic-tree/rendered/{stem}.png"
        mmd_rel = f"agent-logic-tree/{filename}"

        parts.append(f"\n## {heading}\n")
        if png_path.exists():
            parts.append(f"\n![{heading}]({png_rel})\n")
        else:
            parts.append(f"\n_(PNG not rendered yet — run `python scripts/build_logic_tree.py`.)_\n")
        parts.append(
            f"\n<details><summary>Mermaid source — click to expand</summary>\n\n"
            f"```mermaid\n{body}```\n\n"
            f"_Source: [`{filename}`]({mmd_rel})_\n\n"
            f"</details>\n\n---\n"
        )
    return "".join(parts)


IS_WINDOWS = sys.platform == "win32"


def find_renderer() -> list[str] | None:
    """On Windows, mmdc and npx are .cmd shims; shutil.which finds them but
    subprocess needs shell=True (handled in render_image) to invoke them."""
    for candidate in ("mmdc.cmd", "mmdc") if IS_WINDOWS else ("mmdc",):
        if shutil.which(candidate):
            return [candidate]
    for candidate in ("npx.cmd", "npx") if IS_WINDOWS else ("npx",):
        if shutil.which(candidate):
            return [candidate, "-y", "-p", "@mermaid-js/mermaid-cli", "mmdc"]
    return None


def render_image(cmd_prefix: list[str], src: Path, dst: Path, width: int) -> tuple[bool, str]:
    cmd = [*cmd_prefix, "-i", str(src), "-o", str(dst), "-b", "white", "-w", str(width)]
    try:
        result = subprocess.run(
            cmd, check=True, capture_output=True, text=True,
            timeout=240, shell=IS_WINDOWS,
        )
        return True, result.stdout.strip() or "rendered"
    except subprocess.CalledProcessError as e:
        return False, (e.stderr.strip() or e.stdout.strip())[:300]
    except subprocess.TimeoutExpired:
        return False, "render timed out after 240s"
    except FileNotFoundError as e:
        return False, f"command not found: {e}"


def render_all(also_svg: bool) -> bool:
    cmd_prefix = find_renderer()
    if not cmd_prefix:
        print("[render] no mermaid renderer found.")
        print("[render] install: npm install -g @mermaid-js/mermaid-cli")
        return False

    RENDERED_DIR.mkdir(parents=True, exist_ok=True)
    extensions = ["png"] + (["svg"] if also_svg else [])
    print(f"[render] using: {' '.join(cmd_prefix)}")
    print(f"[render] output: {RENDERED_DIR.relative_to(REPO_ROOT)}/")

    failures = []
    for filename, _, width in DIAGRAMS:
        src = TREE_DIR / filename
        if not src.exists():
            print(f"[render]   SKIP {filename} (source missing)")
            continue
        for ext in extensions:
            dst = RENDERED_DIR / f"{src.stem}.{ext}"
            ok, msg = render_image(cmd_prefix, src, dst, width)
            if ok:
                size = dst.stat().st_size if dst.exists() else 0
                print(f"[render]   ok  {src.stem}.{ext}  ({size:,} bytes, w={width})")
            else:
                print(f"[render]   FAIL {src.stem}.{ext}: {msg}")
                failures.append((filename, ext, msg))

    if failures:
        print(f"[render] {len(failures)} failures (markdown still produced).")
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--no-render", action="store_true",
                        help="Skip PNG rendering; produce markdown only.")
    parser.add_argument("--svg", action="store_true",
                        help="Also produce SVG output.")
    args = parser.parse_args()

    if not TREE_DIR.exists():
        sys.exit(f"missing source dir: {TREE_DIR}")

    if not args.no_render:
        render_all(also_svg=args.svg)

    markdown = assemble_markdown()
    OUTPUT_MD.write_text(markdown, encoding="utf-8")
    print(f"[md] wrote {OUTPUT_MD.relative_to(REPO_ROOT)} ({len(markdown):,} bytes)")
    print(f"[md] open the markdown OR view PNGs directly:")
    print(f"[md]   {(RENDERED_DIR / 'core.png').relative_to(REPO_ROOT)}        <- start here")
    print(f"[md]   {(RENDERED_DIR / 'negotiation.png').relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
